### ISSUE TITLE
Crash on clicking on Enchanting Table in 1.21.1 Fabric

### ISSUE THREAD

**Issue by Threndon** [Tfarcenim/Reroll-Enchants#1]
The file is marked as 1.21.1-compatible, but the game does not load at all in 1.21.1, unless I go into the jar file and add 1.21.1 in the "depends" line, then the game loads, but freezes or crashes when I try to access the enchanting table GUI. I've attached the lines from the latest log that seem to relate to this mod - I realise, because I don't know enough about modding - that by adding 1.21.1 in the "depends" field probably has missed something crucial somewhere else, e.g. in the mixins or something, so I apologise if this isn't as helpful as it could otherwise be. Looking forward to being able to use this mod, though!
[latest log.txt](https://github.com/user-attachments/files/16731981/latest.log.txt)

**Comment by Tfarcenim** [comment]
Fixed in 1.21-1

**Comment by Threndon** [comment]
Thank you very much! :D
